export const Routes = {
  ROOT: "/",
  ADMIN: "/admin",
  ADMIN_IAM: "/admin/iam",
  ADMIN_AUDITORS: "/admin/auditors",
  ADMIN_DOCUMENTS: "/admin/documents",
  ADMIN_SEARCH: "/admin/search",
  ADMIN_METRICS: "/admin/metrics",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_PROFILE: "/admin/profile",
  COMPLIANCE: "/compliance",
  COMPLIANCE_LOGS: "/compliance/audit-logs",
  COMPLIANCE_AUDITORS: "/compliance/auditor-activity",
  COMPLIANCE_REPORTS: "/compliance/reports",
  COMPLIANCE_PROFILE: "/compliance/profile",
  COMPLIANCE_SETTINGS: "/compliance/settings",
};
