# Generated by Django 6.0.6 on 2026-07-14 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_auditor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsearchaudit',
            name='event_type',
            field=models.CharField(choices=[('AUDITOR_CREATED', 'Auditor Created'), ('KEY_GENERATED', 'Key Generated'), ('KEY_ROTATED', 'Key Rotated'), ('ACCOUNT_UPDATED', 'Account Updated'), ('ACCOUNT_DELETED', 'Account Deleted'), ('CREDENTIAL_DOWNLOADED', 'Credential Downloaded'), ('EXTERNAL_SEARCH', 'External Search')], db_index=True, default='EXTERNAL_SEARCH', max_length=50),
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalsearchaudit',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_search_logs', to='documents.auditor'),
        ),
        migrations.AlterField(
            model_name='externalsearchaudit',
            name='execution_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalsearchaudit',
            name='keyword_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='externalsearchaudit',
            index=models.Index(fields=['event_type'], name='documents_e_event_t_c62431_idx'),
        ),
    ]
