# Generated by Django 6.0.x on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_auditor_designation_auditor_email_auditor_phone_and_more"),
        ("documents", "0007_externalsearchaudit_event_type_and_more"),
    ]

    operations = []
