# Generated by Django 6.0.6 on 2026-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_sync_organization_code_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='organization_code',
            field=models.CharField(max_length=64),
        ),
    ]
