# Generated by Django 6.0.6 on 2026-07-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_auditor_organization_code'),
        ('documents', '0011_sync_organization_name_field'),
    ]

    operations = [
    ]
