# Generated by Django 6.0.6 on 2026-07-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_merge_20260720_0535'),
        ('documents', '0012_sync_auditor_legacy_credentials_fields'),
    ]

    operations = [
    ]
