# Generated by Django 6.0.6 on 2026-07-20 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_merge_20260720_0557'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='organization_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], db_index=True, default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied')], db_index=True, default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('response_code', models.IntegerField(default=200)),
                ('key_version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_system_logs', to='documents.auditor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='documents_s_created_03ac1a_idx'), models.Index(fields=['action'], name='documents_s_action_e01afd_idx'), models.Index(fields=['severity'], name='documents_s_severit_6b9e15_idx'), models.Index(fields=['status'], name='documents_s_status_66b923_idx'), models.Index(fields=['username'], name='documents_s_usernam_2f3579_idx'), models.Index(fields=['organization'], name='documents_s_organiz_b0728d_idx')],
            },
        ),
    ]
